FROM apache/hadoop:3.3.6

# Cấu hình NameNode
COPY core-site.xml $HADOOP_CONF_DIR/core-site.xml
COPY hdfs-site.xml $HADOOP_CONF_DIR/hdfs-site.xml

# Entrypoint script
COPY entrypoint.sh /entrypoint.sh
USER root
RUN chmod +x /entrypoint.sh

EXPOSE 9870 9000
ENTRYPOINT ["/entrypoint.sh"]
