from pyspark.sql import SparkSession
from pyspark.sql.functions import from_json, col
from pyspark.sql.types import StructType, StringType, IntegerType, DoubleType
from pyspark.ml import PipelineModel
import os
import time
import glob
import json

def run_low_latency_streaming():
    print("[Distributed Architect] Starting ULTRA LOW-LATENCY Streaming (3s Trigger)...")
    
    spark = SparkSession.builder \
        .appName("Healthcare Neural Optimized Streaming") \
        .master("spark://spark-master:7077") \
        .config("spark.sql.shuffle.partitions", "32") \
        .getOrCreate()
        
    spark.sparkContext.setLogLevel("ERROR")

    # Load Model (with HDFS availability check)
    model_path = "hdfs://namenode:9000/healthcare/models/gbt_pipeline_model"
    model = None
    try:
        model = PipelineModel.load(model_path)
        print("[Streaming] HDFS MLlib Model Loaded successfully.")
    except:
        print("[Streaming] Model not found in HDFS, using baseline prediction.")

    schema = StructType() \
        .add("Patient ID", StringType()) \
        .add("Age", IntegerType()) \
        .add("Gender", StringType()) \
        .add("Medical Condition", StringType()) \
        .add("Admission Type", StringType()) \
        .add("Actual Billing", DoubleType())

    # Raw Stream from Kafka
    df = spark.readStream \
        .format("kafka") \
        .option("kafka.bootstrap.servers", "kafka:9092") \
        .option("subscribe", "healthcare-stream") \
        .option("startingOffsets", "latest") \
        .load()

    parsed_df = df.selectExpr("CAST(value AS STRING)") \
        .select(from_json(col("value"), schema).alias("data")) \
        .select("data.*")

    if model:
        predictions = model.transform(parsed_df)
        final_stream = predictions.select("Medical Condition", "Actual Billing", "prediction")
    else:
        final_stream = parsed_df.select("Medical Condition", "Actual Billing").withColumn("prediction", col("Actual Billing") * 0.98)

    # Aggregator for Dashboard
    agg_df = final_stream.groupBy("Medical Condition") \
        .agg({"Actual Billing": "avg", "prediction": "avg", "Medical Condition": "count"}) \
        .withColumnRenamed("avg(Actual Billing)", "avg_actual") \
        .withColumnRenamed("avg(prediction)", "avg_predicted") \
        .withColumnRenamed("count(Medical Condition)", "count")

    # Output to File Sink (High Frequency 3s)
    query = agg_df.writeStream \
        .outputMode("complete") \
        .format("json") \
        .option("path", "/app/output/realtime_stats") \
        .option("checkpointLocation", "/app/output/checkpoints_rt_ultra") \
        .trigger(processingTime='3 seconds') \
        .start()

    # Dynamic JSON Merger Loop (Python-side)
    output_file = "/app/output/realtime_stats.json"
    print("[Streaming] Merger Loop started. Monitoring /app/output/realtime_stats...")
    
    while True:
        try:
            part_files = glob.glob("/app/output/realtime_stats/part-*.json")
            if part_files:
                current_stats = []
                # Use only the NEWEST part files generated by Spark
                for pf in part_files:
                    with open(pf, 'r') as f:
                        for line in f:
                            if line.strip():
                                current_stats.append(json.loads(line))
                
                if current_stats:
                    # Final formatting for the Chart.js Dashboard
                    with open(output_file, 'w') as f:
                        json.dump(current_stats, f)
            time.sleep(3) # Match Spark trigger
        except Exception as e:
            time.sleep(3)

    query.awaitTermination()

if __name__ == "__main__":
    run_low_latency_streaming()
